# Part of the PrefectOS core package — batch_ingest.
"""Deterministic statement extractor: the zero-token fast path.

Parses single-page bank-statement PDFs (DFBK-style layout) with pdfplumber,
rebuilds the transaction table, and verifies the balance chain row-by-row
with pandas. A document that passes every check never touches an LLM.

Exit contract:
    ExtractionResult.status == "clean"      -> ship JSON, seal ledger
    ExtractionResult.status == "exception"  -> route ONLY failing rows to LLM
    ExtractionResult.status == "unreadable" -> route whole doc (scan/OCR tier)
"""
from __future__ import annotations

import re
import time
from dataclasses import dataclass, field
from pathlib import Path

import pandas as pd
import pdfplumber

MONEY = re.compile(r"-?\d{1,3}(?:,\d{3})*\.\d{2}")
ROW_START = re.compile(r"^(\d{4}-\d{2}-\d{2})\s+(TXN\d{13,16})\s+(.*)$")
TOLERANCE = 0.005

CHANNELS = ("NEFT", "RTGS", "IMPS", "UPI", "CHQ", "SWIFT-IN", "SWIFT-OUT", "INT-TRF")

HEADER_PATTERNS = {
    "account_no":      re.compile(r"Account No\s+(\d{8,20})"),
    "ifsc":            re.compile(r"IFSC\s+([A-Z]{4}0[A-Z0-9]{6})"),
    "account_type":    re.compile(r"Account Type\s+(\S+)"),
    "currency":        re.compile(r"Currency\s+([A-Z]{3})"),
    "period":          re.compile(r"Statement Period\s+(\d{4}-\d{2}-\d{2}) to (\d{4}-\d{2}-\d{2})"),
    "opening_balance": re.compile(r"Opening Balance\s+(-?[\d,]+\.\d{2})"),
}


def _num(s: str) -> float:
    return float(s.replace(",", ""))


@dataclass
class ExtractionResult:
    doc_id: str
    status: str = "clean"                       # clean | exception | unreadable
    header: dict = field(default_factory=dict)
    transactions: list = field(default_factory=list)
    exceptions: list = field(default_factory=list)   # row-level failures for the LLM
    totals: dict = field(default_factory=dict)
    elapsed_ms: float = 0.0

    def to_output(self) -> dict:
        return {
            "doc_id": self.doc_id,
            "status": self.status,
            "header": self.header,
            "n_transactions": len(self.transactions),
            "transactions": self.transactions,
            "totals": self.totals,
            "exceptions": self.exceptions,
            "elapsed_ms": round(self.elapsed_ms, 1),
        }


def extract_statement(pdf_path: str | Path, doc_id: str | None = None) -> ExtractionResult:
    t0 = time.perf_counter()
    pdf_path = Path(pdf_path)
    res = ExtractionResult(doc_id=doc_id or pdf_path.stem)

    try:
        with pdfplumber.open(pdf_path) as pdf:
            text = "\n".join((page.extract_text() or "") for page in pdf.pages)
    except Exception as exc:                                   # corrupt / encrypted
        res.status = "unreadable"
        res.exceptions.append({"scope": "document", "reason": f"open_failed: {exc}"})
        res.elapsed_ms = (time.perf_counter() - t0) * 1000
        return res

    if len(text.strip()) < 100:                                # scanned / raster page
        res.status = "unreadable"
        res.exceptions.append({"scope": "document", "reason": "no_text_layer"})
        res.elapsed_ms = (time.perf_counter() - t0) * 1000
        return res

    # ---- header ------------------------------------------------------------
    for key, pat in HEADER_PATTERNS.items():
        m = pat.search(text)
        if not m:
            res.exceptions.append({"scope": "header", "field": key, "reason": "not_found"})
            continue
        if key == "period":
            res.header["period_from"], res.header["period_to"] = m.group(1), m.group(2)
        elif key == "opening_balance":
            res.header[key] = _num(m.group(1))
        else:
            res.header[key] = m.group(1)

    # ---- transaction blocks (rows wrap; accumulate until amount+balance) ---
    rows, current = [], None
    for line in text.splitlines():
        m = ROW_START.match(line.strip())
        if m:
            if current is not None:
                rows.append(current)
            current = {"date": m.group(1), "txn_id": m.group(2), "raw": m.group(3)}
        elif current is not None and not line.startswith(("Totals:", "Generated by", "Date Txn ID")):
            current["raw"] += " " + line.strip()
    if current is not None:
        rows.append(current)

    parsed = []
    for r in rows:
        amounts = MONEY.findall(r["raw"])
        if len(amounts) < 2:
            res.exceptions.append({"scope": "row", "txn_id": r["txn_id"],
                                   "raw": r["raw"], "reason": "amounts_not_found"})
            continue
        balance, amount = _num(amounts[-1]), _num(amounts[-2])
        narration = MONEY.sub("", r["raw"]).strip()
        channel = next((c for c in CHANNELS if narration.startswith(c)), None)
        if channel is None:
            res.exceptions.append({"scope": "row", "txn_id": r["txn_id"],
                                   "raw": r["raw"], "reason": "unknown_channel"})
        parsed.append({"date": r["date"], "txn_id": r["txn_id"], "narration": narration,
                       "channel": channel, "amount": amount, "balance": balance})

    if not parsed:
        res.status = "exception"
        res.exceptions.append({"scope": "document", "reason": "no_rows_parsed"})
        res.elapsed_ms = (time.perf_counter() - t0) * 1000
        return res

    # ---- balance-chain + totals validation with pandas ---------------------
    df = pd.DataFrame(parsed)
    opening = res.header.get("opening_balance")
    prev = opening
    debits = credits = 0.0
    for i, row in df.iterrows():
        if prev is None:
            break
        delta = row["balance"] - prev
        if abs(abs(delta) - row["amount"]) > TOLERANCE:
            res.exceptions.append({"scope": "row", "txn_id": row["txn_id"],
                                   "raw": rows[i]["raw"],
                                   "reason": "balance_chain_break",
                                   "expected_delta": round(row["amount"], 2),
                                   "observed_delta": round(abs(delta), 2)})
            df.loc[i, "direction"] = "unknown"
        else:
            direction = "credit" if delta > 0 else "debit"
            df.loc[i, "direction"] = direction
            if direction == "debit":
                debits += row["amount"]
            else:
                credits += row["amount"]
        prev = row["balance"]

    totals_m = re.search(
        r"Totals:\s*Debits\s+(-?[\d,]+\.\d{2})\s*\|\s*Credits\s+(-?[\d,]+\.\d{2})"
        r"\s*\|\s*Closing Balance\s+(-?[\d,]+\.\d{2})", text)
    if totals_m:
        stated = {"debits": _num(totals_m.group(1)), "credits": _num(totals_m.group(2)),
                  "closing_balance": _num(totals_m.group(3))}
        computed = {"debits": round(debits, 2), "credits": round(credits, 2),
                    "closing_balance": round(float(df.iloc[-1]["balance"]), 2)}
        res.totals = {"stated": stated, "computed": computed}
        for k in stated:
            if abs(stated[k] - computed[k]) > TOLERANCE:
                res.exceptions.append({"scope": "totals", "field": k,
                                       "reason": "mismatch",
                                       "stated": stated[k], "computed": computed[k]})
    else:
        res.exceptions.append({"scope": "totals", "reason": "totals_line_not_found"})

    res.transactions = df.to_dict("records")
    if res.exceptions:
        res.status = "exception"
    res.elapsed_ms = (time.perf_counter() - t0) * 1000
    return res
