# Part of the PrefectOS core package — batch_ingest.
"""Per-document HTML report — generated by the worker in the same second the
document reaches its terminal state.

Design constraints (deliberate):
  - 100% self-contained: inline CSS, system fonts, zero network fetches, so
    the file renders identically in air-gapped BFSI environments and email.
  - Reads like a reconciliation register, not a dashboard: ruled tables,
    monospace figures, and a teller-style status stamp.
  - The footer strip carries the output SHA-256 and ledger reference so the
    report itself points at its tamper-evidence.
"""
from __future__ import annotations

import html
from datetime import datetime

STATUS_META = {
    "clean":            ("VERIFIED", "Deterministic checks passed — no AI used",
                         "#1E6B4E"),
    "resolved_by_llm":  ("AI-REPAIRED", "Flagged rows repaired by governed AI call",
                         "#8A5A00"),
    "escalated_hitl":   ("HUMAN REVIEW", "Routed to reviewer — do not consume yet",
                         "#A33B2E"),
    "failed":           ("FAILED", "Processing error — see exceptions",
                         "#A33B2E"),
}


def _e(v) -> str:
    return html.escape(str(v)) if v is not None else "—"


def _amt(v) -> str:
    if v in (None, ""):
        return ""
    return f"{v:,.2f}"


def render_report(payload: dict, batch_id: str = "", ledger_ref: str = "") -> str:
    status = payload.get("status", "clean")
    if status == "exception":
        status = "escalated_hitl"
    label, subtitle, color = STATUS_META.get(status, STATUS_META["failed"])
    hdr = payload.get("header", {})
    txns = payload.get("transactions", [])
    totals = payload.get("totals", {})
    exceptions = payload.get("exceptions", [])
    stated, computed = totals.get("stated", {}), totals.get("computed", {})
    repaired = sum(1 for t in txns if t.get("repaired_by"))
    now = datetime.now().strftime("%d %b %Y, %H:%M:%S")
    sha = payload.get("_output_sha256", "")

    def tick(a, b):
        if a is None or b is None:
            return '<span class="x">—</span>'
        return ('<span class="ok">✓ match</span>' if abs(a - b) < 0.01
                else '<span class="x">✗ mismatch</span>')

    totals_rows = "".join(
        f'<tr><td>{name}</td><td class="num">{_amt(stated.get(k))}</td>'
        f'<td class="num">{_amt(computed.get(k))}</td>'
        f'<td>{tick(stated.get(k), computed.get(k))}</td></tr>'
        for name, k in (("Debits", "debits"), ("Credits", "credits"),
                        ("Closing balance", "closing_balance"))) if totals else \
        '<tr><td colspan="4" class="muted">Totals line not present in document</td></tr>'

    txn_rows = []
    for t in txns:
        rep = ' class="rep"' if t.get("repaired_by") else ""
        d = _amt(t["amount"]) if t.get("direction") == "debit" else ""
        c = _amt(t["amount"]) if t.get("direction") == "credit" else ""
        bal = t.get("balance")
        neg = ' style="color:#A33B2E"' if isinstance(bal, (int, float)) and bal < 0 else ""
        txn_rows.append(
            f'<tr{rep}><td class="mono">{_e(t.get("date"))}</td>'
            f'<td class="mono small">{_e(t.get("txn_id"))}</td>'
            f'<td>{_e(t.get("channel"))}</td>'
            f'<td class="narr">{_e(t.get("narration"))}'
            f'{" <b>· AI-repaired</b>" if t.get("repaired_by") else ""}</td>'
            f'<td class="num">{d}</td><td class="num">{c}</td>'
            f'<td class="num"{neg}>{_amt(bal)}</td></tr>')

    exc_html = ""
    if exceptions:
        items = "".join(
            f'<tr><td class="mono small">{_e(e.get("txn_id", e.get("scope")))}</td>'
            f'<td>{_e(e.get("reason"))}</td>'
            f'<td class="narr small">{_e(e.get("raw", ""))[:160]}</td></tr>'
            for e in exceptions)
        exc_html = f"""
  <h2>Flagged rows ({len(exceptions)})</h2>
  <table class="grid"><thead><tr><th>Row</th><th>Reason</th><th>Raw text</th></tr></thead>
  <tbody>{items}</tbody></table>"""

    period = f'{_e(hdr.get("period_from"))} → {_e(hdr.get("period_to"))}'
    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Processing report — {_e(payload.get("doc_id"))}</title>
<style>
:root{{--ink:#1B2431;--rule:#D5DDE9;--faint:#F3F6FA;--muted:#66707F;--stamp:{color}}}
*{{box-sizing:border-box;margin:0}}
body{{font:14px/1.5 system-ui,-apple-system,"Segoe UI",Roboto,sans-serif;
  color:var(--ink);background:#fff;max-width:920px;margin:0 auto;padding:32px 28px}}
.mono,.num{{font-family:ui-monospace,"Cascadia Mono","SF Mono",Menlo,Consolas,monospace}}
.small{{font-size:12px}}.muted{{color:var(--muted)}}
header{{display:flex;justify-content:space-between;align-items:flex-start;
  border-bottom:3px double var(--ink);padding-bottom:18px;margin-bottom:22px}}
.eyebrow{{font-size:11px;letter-spacing:.18em;text-transform:uppercase;color:var(--muted)}}
h1{{font-size:22px;margin-top:2px}} h1 .mono{{font-size:19px}}
h2{{font-size:12px;letter-spacing:.14em;text-transform:uppercase;
  margin:26px 0 8px;color:var(--muted)}}
.stamp{{border:3px solid var(--stamp);color:var(--stamp);border-radius:8px;
  padding:8px 16px;text-align:center;transform:rotate(-4deg);
  font-weight:800;letter-spacing:.12em;font-size:15px;max-width:220px}}
.stamp small{{display:block;font-weight:400;letter-spacing:0;font-size:10.5px;
  text-transform:none;margin-top:3px}}
.fields{{display:grid;grid-template-columns:repeat(3,1fr);gap:0;border:1px solid var(--rule)}}
.f{{padding:8px 12px;border-right:1px solid var(--rule);border-bottom:1px solid var(--rule)}}
.f:nth-child(3n){{border-right:none}}
.f b{{display:block;font-size:10.5px;letter-spacing:.1em;text-transform:uppercase;
  color:var(--muted);font-weight:600}}
table.grid{{width:100%;border-collapse:collapse;font-size:13px}}
.grid th{{text-align:left;font-size:10.5px;letter-spacing:.1em;text-transform:uppercase;
  color:var(--muted);border-bottom:2px solid var(--ink);padding:6px 8px}}
.grid td{{padding:6px 8px;border-bottom:1px solid var(--rule);vertical-align:top}}
.grid .num{{text-align:right;white-space:nowrap}}
.grid tr.rep td{{background:#FBF4E3}}
.narr{{max-width:340px}}
.ok{{color:#1E6B4E;font-weight:700}}.x{{color:#A33B2E;font-weight:700}}
.figs{{display:flex;gap:0;border:1px solid var(--rule);margin-top:6px}}
.figs div{{flex:1;padding:10px 14px;border-right:1px solid var(--rule)}}
.figs div:last-child{{border-right:none}}
.figs b{{display:block;font-size:10.5px;letter-spacing:.1em;text-transform:uppercase;
  color:var(--muted);font-weight:600}}
.figs span{{font-size:16px}}
footer{{margin-top:30px;border-top:1px dashed var(--ink);padding-top:12px;
  font-size:11.5px;color:var(--muted)}}
footer .mono{{word-break:break-all;color:var(--ink)}}
@media print{{body{{padding:0}}.stamp{{transform:rotate(-4deg)}}}}
</style></head><body>
<header>
  <div>
    <div class="eyebrow">PrefectOS · Governed document processing</div>
    <h1>Processing report — <span class="mono">{_e(payload.get("doc_id"))}</span></h1>
    <div class="small muted">Generated {now}{f" · Batch {_e(batch_id)}" if batch_id else ""}
      · Processed in {_e(payload.get("elapsed_ms"))} ms</div>
  </div>
  <div class="stamp">{label}<small>{subtitle}</small></div>
</header>

<h2>Account</h2>
<div class="fields">
  <div class="f"><b>Account no</b><span class="mono">{_e(hdr.get("account_no"))}</span></div>
  <div class="f"><b>IFSC</b><span class="mono">{_e(hdr.get("ifsc"))}</span></div>
  <div class="f"><b>Type / currency</b>{_e(hdr.get("account_type"))} · {_e(hdr.get("currency"))}</div>
  <div class="f"><b>Statement period</b><span class="mono small">{period}</span></div>
  <div class="f"><b>Opening balance</b><span class="mono">{_amt(hdr.get("opening_balance"))}</span></div>
  <div class="f"><b>Rows extracted</b><span class="mono">{len(txns)}</span>{f' · <span class="mono">{repaired}</span> AI-repaired' if repaired else ""}</div>
</div>

<h2>Reconciliation — stated by document vs recomputed</h2>
<table class="grid"><thead><tr><th></th><th style="text-align:right">Stated</th>
<th style="text-align:right">Recomputed</th><th>Check</th></tr></thead>
<tbody>{totals_rows}</tbody></table>
{exc_html}

<h2>Transactions ({len(txns)})</h2>
<table class="grid"><thead><tr><th>Date</th><th>Txn ID</th><th>Channel</th>
<th>Narration</th><th style="text-align:right">Debit</th>
<th style="text-align:right">Credit</th><th style="text-align:right">Balance</th></tr></thead>
<tbody>{''.join(txn_rows)}</tbody></table>

<footer>
  Output SHA-256: <span class="mono">{_e(sha) if sha else "sealed at write time"}</span><br>
  Ledger reference: <span class="mono">{_e(ledger_ref) if ledger_ref else "batch decision ledger, doc_processed entry"}</span> —
  verify integrity with <span class="mono">python batch_ledger.py verify-all</span>.
  This report was generated deterministically from the sealed output; regenerate at any time from the JSON.
</footer>
</body></html>"""
