"""Application-stage loan documents, aligned with the processing prompts.

Rendering-agnostic content: every builder returns a list of pages, each a
(title, lines) pair. A line is plain text, "## Heading", or "@@Label|Value"
(a label/value row laid out the way loan_extractors._labelled reads it).
application_kit.py renders these as PDF (minipdf) and Excel (minixlsx) for
demo_kit/loan_kit/bundles*; samples/build_email_packs.py renders the same
content as email-intake packs.

Six packs, one fictional applicant each, built against the criteria in
loan_processing.DEFAULT_PROMPTS for home / vehicle / personal loans:

    home_loan_application_positive       ELIGIBLE
    home_loan_application_negative       NOT_ELIGIBLE  (+ a tampered salary slip)
    vehicle_loan_application_positive    ELIGIBLE
    vehicle_loan_application_negative    NOT_ELIGIBLE
    personal_loan_application_positive   ELIGIBLE
    personal_loan_application_negative   NOT_ELIGIBLE

Salary slips carry the exact labels and western money format the
deterministic extractor parses, so they reconcile in code. No document other
than a salary slip may contain an extractor type marker ("SALARY SLIP",
"SANCTION LETTER", ...) — the engine would parse it as that type and lose it.
Every page is stamped SPECIMEN; nothing here is a real person or record.
"""
from __future__ import annotations

from dataclasses import dataclass

STAMP = ("SPECIMEN - synthetic demo data generated by application_docs.py. "
         "Not a real customer, account or document.")
MONTHS = ["March 2026", "April 2026", "May 2026", "June 2026", "July 2026", "August 2026"]
BANK_MONTHS = [("01-03-2026", "31-03-2026"), ("01-04-2026", "30-04-2026"),
               ("01-05-2026", "31-05-2026"), ("01-06-2026", "30-06-2026"),
               ("01-07-2026", "31-07-2026"), ("01-08-2026", "31-08-2026")]


def money(v: float) -> str:
    """Western grouping with two decimals - the only form the extractor reads."""
    return f"{v:,.2f}"


def emi_for(principal: float, annual_rate: float, months: int) -> float:
    r = annual_rate / 1200.0
    return round(principal * r * (1 + r) ** months / ((1 + r) ** months - 1), 2)


# ── The applicant ──────────────────────────────────────────────────────
@dataclass
class Applicant:
    name: str
    dob: str          # dd-mm-yyyy
    age: int
    pan: str
    aadhaar: str      # masked
    address: str
    employer: str
    designation: str
    years_in_job: int
    basic: float
    hra: float
    special: float
    pf: float
    tds: float
    account: str
    ifsc: str
    bank: str
    phone: str

    @property
    def gross(self) -> float:
        return round(self.basic + self.hra + self.special, 2)

    @property
    def deductions(self) -> float:
        return round(self.pf + self.tds, 2)

    @property
    def net(self) -> float:
        return round(self.gross - self.deductions, 2)


# ── Document builders (each returns a list of (title, lines) pages) ────
def identity_pages(a: Applicant, licence: dict | None = None):
    pages = [("PERMANENT ACCOUNT NUMBER CARD", [
        "INCOME TAX DEPARTMENT        GOVT. OF INDIA",
        "", f"Permanent Account Number: {a.pan}",
        f"Name: {a.name.upper()}", f"Date of birth: {a.dob}", "",
        f"Signature: {a.name}",
    ]), ("AADHAAR - Unique Identification Authority of India", [
        f"Aadhaar number: {a.aadhaar}",
        f"Name: {a.name}        DOB: {a.dob}",
        f"Address: {a.address}", "",
        "Aadhaar is a proof of identity, not of citizenship.",
    ])]
    if licence:
        pages.append(("DRIVING LICENCE - Transport Department, Karnataka", [
            f"Licence number: {licence['number']}",
            f"Name: {a.name}        DOB: {a.dob}",
            f"Address: {a.address}",
            f"Class of vehicle: LMV (light motor vehicle)",
            f"Date of issue: {licence['issued']}        Valid till: {licence['valid_till']}",
            "" if licence.get("valid", True) else "STATUS: EXPIRED - renewal not recorded.",
        ]))
    return pages


def salary_pages(a: Applicant, months=MONTHS, tamper_gross: float | None = None):
    """Six slips laid out exactly as loan_extractors.parse_salary_slip reads:
    `Label   value` rows, western money, NET PAY in capitals."""
    pages = []
    for i, month in enumerate(months):
        # The extractor reads the FIRST slip in the file, so a seeded tamper
        # goes on slip 1 (March) to be caught in code.
        tampered = bool(tamper_gross) and i == 0
        gross = tamper_gross if tampered else a.gross
        net = round(gross - a.deductions, 2) if tampered else a.net
        pages.append((f"SALARY SLIP - {month}", [
            f"Employer: {a.employer}",
            f"@@Employee|{a.name}",
            f"@@Employee ID|EMP-{a.pan[-4:]}",
            f"@@Designation|{a.designation}",
            f"PAN: {a.pan}        Bank A/c: {a.account}",
            "", "## Earnings",
            f"@@Basic|{money(a.basic)}",
            f"@@HRA|{money(a.hra)}",
            f"@@Special Allowance|{money(a.special)}",
            f"@@Gross Earnings|{money(gross)}",
            "", "## Deductions",
            f"@@Provident Fund|{money(a.pf)}",
            f"@@Income Tax (TDS)|{money(a.tds)}",
            f"@@Total Deductions|{money(a.deductions)}",
            "",
            f"@@NET PAY|{money(net)}",
            "", "Computer generated; no signature required.",
        ]))
    pages.append(("FORM 16 - Certificate under section 203 of the Income-tax Act (FY 2025-26)", [
        f"Employer: {a.employer}        TAN: BLR{a.pan[:5]}A",
        f"Employee: {a.name}        PAN: {a.pan}",
        f"Period of employment in FY: full year        Years with employer: {a.years_in_job}",
        "",
        f"@@Gross salary (total income from salary)|{money(a.gross * 12)}",
        f"@@Total income|{money(a.gross * 12 - a.pf * 12)}",
        f"@@Tax deducted at source|{money(a.tds * 12)}",
        "", "Verified by: Head of Finance",
    ]))
    return pages


def bank_statement_pages(a: Applicant, salary_credit: float, extra_debits=(), label_note=""):
    """Six monthly savings statements with the salary credit each month.
    Never says 'LOAN ACCOUNT STATEMENT' or 'SALARY SLIP' (other parsers)."""
    pages = []
    balance = 214_500.00
    for (start, end), month in zip(BANK_MONTHS, MONTHS):
        rows = [(start, "Opening balance", "", "", balance)]
        balance = round(balance + salary_credit, 2)
        rows.append((start, f"NEFT SALARY {a.employer.split()[0].upper()}", "", salary_credit, balance))
        for day, desc, amt in (("05", "UPI RENT", 38_000.00), ("09", "CARD PAYMENT", 22_400.00),
                               ("14", "UPI GROCERIES", 6_240.00), ("20", "INSURANCE PREMIUM", 8_500.00)):
            balance = round(balance - amt, 2)
            rows.append((f"{day}-{start[3:]}", desc, amt, "", balance))
        for day, desc, amt in extra_debits:
            balance = round(balance - amt, 2)
            rows.append((f"{day}-{start[3:]}", desc, amt, "", balance))
        rows.append((end, "Closing balance", "", "", balance))
        lines = [f"{a.bank} - Savings account statement",
                 f"Account holder: {a.name}",
                 f"Account number: {a.account}        IFSC: {a.ifsc}",
                 f"Statement period: {start} to {end}", "",
                 "Date         Transaction                      Debit         Credit        Balance"]
        for d, desc, dr, cr, bal in rows:
            lines.append(f"{d:<12} {desc:<30} {money(dr) if dr else '':>12}  {money(cr) if cr else '':>12}  {money(bal):>14}")
        lines += ["", f"Opening balance: {money(rows[0][4])}        Closing balance: {money(balance)}",
                  f"Salary credit this month: {money(salary_credit)}"]
        if label_note:
            lines.append(label_note)
        pages.append((f"ACCOUNT STATEMENT - {month}", lines))
    return pages


def credit_report_pages(a: Applicant, score: int, accounts: list[str], remarks: list[str],
                        delinquency: str = "None in the last 24 months"):
    return [("CREDIT REPORT - Consumer credit bureau summary", [
        f"Consumer: {a.name}        DOB: {a.dob}        PAN: {a.pan}",
        "Report date: 01-09-2026        Bureau: TransUnion CIBIL (specimen)",
        "", f"## Credit score: {score}",
        "Score range 300-900. Bureau band: " + ("Excellent" if score >= 750 else "Good" if score >= 700 else "Fair" if score >= 650 else "Poor"),
        "", "## Accounts",
        *(f"  - {x}" for x in accounts),
        "", "## Payment history",
        f"Days past due (max, last 12 months): {delinquency}",
        "", "## Write-offs / settlements (last 24 months)",
        *(f"  - {x}" for x in remarks),
        "", "## Enquiries (last 6 months): 1 (this application)",
    ])]


def application_pages(a: Applicant, product_label: str, amount: float, months: int, rate: float,
                      purpose: str, extra_lines: list[str], enclosed: list[str],
                      existing_emi: float = 0.0, active_unsecured: int = 0):
    emi = emi_for(amount, rate, months)
    return [("LOAN APPLICATION FORM", [
        f"Product applied: {product_label}",
        f"Applicant name: {a.name}",
        f"Date of birth: {a.dob} (age {a.age})        PAN: {a.pan}        Aadhaar: {a.aadhaar}",
        f"Residential address: {a.address}",
        f"Mobile: {a.phone}",
        "", "## Loan requested",
        f"@@Loan amount (Rs)|{money(amount)}",
        f"@@Tenure|{months} months",
        f"@@Interest rate|{rate:.2f}% p.a.",
        f"@@Proposed EMI (Rs)|{money(emi)}",
        f"Age at loan maturity: {a.age + months // 12}",
        f"Purpose: {purpose}",
        *extra_lines,
        "", "## Employment and income",
        f"Employer: {a.employer}        Designation: {a.designation}",
        f"Employment type: Salaried        Years in current job: {a.years_in_job}",
        f"@@Gross monthly income (Rs)|{money(a.gross)}",
        f"@@Net monthly income (Rs)|{money(a.net)}",
        f"@@EMI to net income|{emi / a.net * 100:.2f}%",
        "", "## Existing obligations",
        f"@@Existing EMIs per month (Rs)|{money(existing_emi)}",
        f"Active unsecured loans: {active_unsecured}",
        "", "## Declaration",
        "I declare that the information given in this loan application is true and complete.",
        f"Signature: {a.name}        Date: 01-09-2026",
    ]), ("LOAN APPLICATION FORM - Annexure: documents enclosed", [
        "## Documents enclosed with this loan application",
        *(f"  - {d}" for d in enclosed),
    ])], emi


def property_pages(a: Applicant, value: float, clear_title: bool, building_plan: bool):
    ec = ["No encumbrances found for the above period."] if clear_title else [
        "Entry 1: Mortgage by deposit of title deeds in favour of Southern Housing Finance,",
        "         registered 12-02-2024, for Rs 3,500,000.00 - NOT DISCHARGED.",
        "Entry 2: Lis pendens - O.S. 412/2025, City Civil Court, Bengaluru (pending)."]
    pages = [("SALE DEED", [
        "THIS SALE DEED is executed on 20-08-2026 at Bengaluru", "",
        "BETWEEN  Mr. Venkatesh Gowda, s/o late Krishnappa (the VENDOR)",
        f"AND      {a.name} (the PURCHASER)", "",
        "## Property schedule",
        "Residential apartment No. 302, third floor, 'Lakeview Residency', Whitefield,",
        "Bengaluru 560066, 1,240 sq ft super built-up, one covered car park, with",
        "undivided share of land. Khata No. 118/302, BBMP Mahadevapura zone.",
        "", "## Consideration",
        f"@@Total sale consideration (Rs)|{money(value)}",
        "", "## Title",
        "The vendor holds the property under a registered conveyance dated 03-05-2011;",
        "title chain annexed.",
        "The vendor declares the property is free from all encumbrances, charges and litigation."
        if clear_title else
        "The vendor's declaration on encumbrances is contradicted by the encumbrance certificate annexed.",
    ]), ("SALE DEED - Annexure A: Encumbrance Certificate", [
        "Sub-Registrar Office, Varthur",
        "Encumbrance certificate for the period 01-01-2010 to 15-08-2026",
        "Property: Apartment 302, Lakeview Residency, Whitefield (Khata 118/302)", "",
        *ec,
    ]), ("SALE DEED - Annexure B: Valuation report", [
        "Empanelled valuer: R. Nair & Associates (specimen)        Date: 18-08-2026",
        "Property: Apartment 302, Lakeview Residency, Whitefield", "",
        f"@@Fair market value (Rs)|{money(value)}",
        f"@@Realisable value (Rs)|{money(round(value * 0.9, 2))}",
        "Construction: RCC framed, completed 2018, good condition.",
    ])]
    pages.append(("SALE DEED - Annexure C: Approved building plan", [
        "BBMP building plan sanction No. BBMP/Addl.Dir/JDTP/East/0123/2016-17",
        "Sanctioned 14-06-2016 for 'Lakeview Residency', 4 floors, 24 units.",
        "Occupancy certificate issued 22-11-2018.",
    ] if building_plan else [
        "No sanctioned building plan or occupancy certificate could be produced for",
        "'Lakeview Residency'. The builder's letter states the plan approval is 'applied for'.",
    ]))
    return pages


def vehicle_invoice_pages(a: Applicant, ex_showroom: float, on_road: float, model: str):
    return [("PROFORMA INVOICE - Trident Motors Pvt Ltd (authorised dealer, specimen)", [
        f"Customer: {a.name}        Address: {a.address}",
        f"Vehicle: {model}        Variant: SX (O) petrol AT        Colour: Atlas white",
        "", f"@@Ex-showroom price (Rs)|{money(ex_showroom)}",
        f"@@Registration and road tax (Rs)|{money(round(ex_showroom * 0.13, 2))}",
        f"@@Insurance - comprehensive, 1 year (Rs)|{money(round(ex_showroom * 0.035, 2))}",
        f"@@On-road price (Rs)|{money(on_road)}",
        "Chassis / engine numbers to be allotted on delivery. Quotation valid 30 days.",
        f"Vehicle to be registered in the name of: {a.name}, {a.address}",
        f"Comprehensive insurance proposer / policyholder: {a.name} (proposal attached to this quotation)",
        f"Hypothecation to be endorsed in favour of the financing bank on registration.",
    ])]


# ── Applicants (one per pack) ──────────────────────────────────────────
def applicant(name, dob, age, pan, addr, employer, desig, years, basic, hra, special, pf, tds,
              acct, ifsc, bank, phone) -> Applicant:
    return Applicant(name, dob, age, pan, "XXXX XXXX " + pan[-4:].replace("K", "4").replace("P", "2"),
                     addr, employer, desig, years, basic, hra, special, pf, tds, acct, ifsc, bank, phone)


HOME_POS = applicant("Rahul Sharma", "14-03-1988", 38, "ABCPS1234K",
                     "Flat 302, Lakeview Residency, Whitefield, Bengaluru 560066",
                     "Nimbus Analytics Pvt Ltd", "Senior Data Engineer", 4,
                     90_000, 45_000, 45_000, 10_800, 27_200, "50100234567890", "HDFC0001234", "HDFC Bank", "+91 98450 12345")
HOME_NEG = applicant("Deepak Rao", "22-07-1990", 36, "AKLPR7781Q",
                     "12, 4th Cross, Indiranagar, Bengaluru 560038",
                     "Coastal Retail Ventures LLP", "Store Manager", 2,
                     40_000, 16_000, 9_000, 4_800, 3_200, "20034455667788", "ICIC0004455", "ICICI Bank", "+91 98861 55443")
VEH_POS = applicant("Priya Menon", "05-11-1992", 33, "BNZPM4412L",
                    "Villa 18, Palm Meadows, Ramagondanahalli, Bengaluru 560066",
                    "Helix Biosciences Ltd", "Product Manager", 5,
                    85_000, 42_500, 32_500, 10_200, 24_800, "30012345678901", "AXIS0002211", "Axis Bank", "+91 99001 22334")
VEH_NEG = applicant("Arjun Iyer", "30-01-1997", 29, "CQRPI9023M",
                    "45, 2nd Main, BTM Layout, Bengaluru 560076",
                    "QuickServe Logistics Pvt Ltd", "Dispatch Executive", 1,
                    28_000, 11_200, 8_800, 3_360, 1_640, "40098765432109", "KKBK0008899", "Kotak Mahindra Bank", "+91 97400 11223")
PER_POS = applicant("Sneha Kulkarni", "19-09-1991", 34, "DHXPK5567R",
                    "Flat 7B, Prestige Sunrise, Electronic City, Bengaluru 560100",
                    "Orbital Fintech Pvt Ltd", "Finance Controller", 6,
                    80_000, 40_000, 30_000, 9_600, 23_400, "60011223344556", "SBIN0011223", "State Bank of India", "+91 96110 44556")
PER_NEG = applicant("Vikram Nair", "08-04-1986", 40, "EPMPN3390T",
                    "22, 8th Cross, Jayanagar, Bengaluru 560041",
                    "Meridian Hospitality Services", "Assistant Manager", 3,
                    38_000, 15_200, 11_800, 4_560, 2_940, "70099887766554", "UTIB0003344", "Axis Bank", "+91 95380 66778")


# ── Packs ──────────────────────────────────────────────────────────────
def build_home(positive: bool):
    a = HOME_POS if positive else HOME_NEG
    if positive:
        value, amount, months, rate = 8_500_000.00, 6_000_000.00, 240, 8.50   # LTV 70.6%
    else:
        value, amount, months, rate = 8_400_000.00, 8_000_000.00, 240, 8.50   # LTV 95.2%
    app, emi = application_pages(
        a, "Home Loan", amount, months, rate,
        "Purchase of residential apartment 302, Lakeview Residency, Whitefield",
        [f"@@Property value as per valuation (Rs)|{money(value)}",
         f"@@Loan to value|{amount / value * 100:.1f}%"],
        ["PAN and Aadhaar", "Pay slips for six months and Form 16", "Sale deed with EC, valuation and building plan",
         "Savings account statements (6 months)", "Credit bureau report"],
        existing_emi=0.0 if positive else 12_500.00)
    docs = {
        "01_loan_application_form.pdf": app,
        "02_identity_proof_pan_aadhaar.pdf": identity_pages(a),
        "03_income_proof_salary_form16.pdf": salary_pages(a, tamper_gross=None if positive else 92_000.00),
        "04_property_sale_deed_ec_valuation.pdf": property_pages(a, value, clear_title=positive, building_plan=positive),
        "05_bank_statements_6_months.pdf": bank_statement_pages(a, a.net),
        "06_credit_report.pdf": credit_report_pages(
            a, 782 if positive else 641,
            ["Credit card - Rs 200,000 limit, current, 0 overdue"] if positive else
            ["Personal loan - Rs 400,000, written off 03-2025 (Rs 118,000 outstanding at write-off)",
             "Credit card - settled for less than the full amount, 08-2025",
             "Two-wheeler loan - current, EMI Rs 12,500"],
            ["None"] if positive else ["Personal loan WRITTEN OFF 03-2025", "Credit card SETTLED 08-2025"],
            delinquency="None in the last 24 months" if positive else "90+ days (personal loan, 2025)"),
    }
    expect = (
        ["ELIGIBLE", f"age {a.age}, {a.age + 20} at maturity; 6 months of stable salary credits matching slips",
         f"FOIR {emi / a.net * 100:.1f}% (EMI {money(emi)} / net {money(a.net)})", f"LTV {amount / value * 100:.1f}%",
         "credit score 782, no write-offs", "clear EC, approved building plan + OC, valuation annexed", "KYC complete"]
        if positive else
        ["NOT_ELIGIBLE", f"FOIR {emi / a.net * 100:.1f}% (EMI {money(emi)} / net {money(a.net)}) - above 50%",
         f"LTV {amount / value * 100:.1f}% - above 80%", "credit score 641 with a write-off (03-2025) and a settlement (08-2025)",
         "EC shows an undischarged mortgage and pending litigation; no approved building plan",
         "March salary slip tampered: Gross Earnings 92,000.00 vs components 65,000.00 (extractor flags gross_mismatch)"])
    return a, docs, expect


def build_vehicle(positive: bool):
    a = VEH_POS if positive else VEH_NEG
    model = "Hyundai Creta 1.5 SX (O)" if positive else "Toyota Fortuner 4x2 AT"
    if positive:
        ex_showroom, amount, months, rate = 1_520_000.00, 1_200_000.00, 60, 9.50    # LTV 78.9%
    else:
        ex_showroom, amount, months, rate = 3_850_000.00, 3_800_000.00, 84, 9.50    # LTV 98.7%
    on_road = round(ex_showroom * 1.165, 2)
    licence = {"number": "KA05 20150012345", "issued": "12-06-2015", "valid_till": "11-06-2035", "valid": True} if positive \
        else {"number": "KA01 20160098765", "issued": "03-02-2016", "valid_till": "02-02-2026", "valid": False}
    app, emi = application_pages(
        a, "Vehicle Loan", amount, months, rate,
        f"Purchase of new car - {model}",
        [f"@@Ex-showroom price (Rs)|{money(ex_showroom)}", f"@@Loan to ex-showroom value|{amount / ex_showroom * 100:.1f}%",
         f"Driving licence: {licence['number']} valid till {licence['valid_till']}"],
        ["PAN, Aadhaar and driving licence", "Pay slips for six months and Form 16", "Dealer proforma invoice with insurance",
         "Savings account statements (6 months)", "Credit bureau report"],
        existing_emi=0.0 if positive else 9_800.00)
    docs = {
        "01_loan_application_form.pdf": app,
        "02_identity_proof_pan_aadhaar_licence.pdf": identity_pages(a, licence),
        "03_income_proof_salary_form16.pdf": salary_pages(a),
        "04_vehicle_proforma_invoice.pdf": vehicle_invoice_pages(a, ex_showroom, on_road, model),
        "05_bank_statements_6_months.pdf": bank_statement_pages(a, a.net),
        "06_credit_report.pdf": credit_report_pages(
            a, 760 if positive else 612,
            ["Credit card - Rs 150,000 limit, current, 0 overdue",
             "Vehicle / auto loans: NONE held, past or present - no vehicle-loan default on record",
             "Secured loans: none"] if positive else
            ["Two-wheeler loan - Rs 95,000, DEFAULT: 120+ days past due, repossessed 11-2025",
             "Consumer durable loan - current, EMI Rs 9,800"],
            ["None"] if positive else ["Two-wheeler loan reported as default / repossession 11-2025"],
            delinquency="None in the last 24 months" if positive else "120+ days (two-wheeler loan, 2025)"),
    }
    expect = (
        ["ELIGIBLE", f"age {a.age}; licence valid till 2035", f"EMI-to-income {emi / a.net * 100:.1f}% (EMI {money(emi)} / net {money(a.net)})",
         f"LTV {amount / ex_showroom * 100:.1f}% of ex-showroom", "credit score 760, no vehicle-loan default",
         "proforma invoice, insurance and registration in the applicant's name", "KYC complete"]
        if positive else
        ["NOT_ELIGIBLE", "driving licence EXPIRED 02-02-2026", f"EMI-to-income {emi / a.net * 100:.1f}% - above 45%",
         f"LTV {amount / ex_showroom * 100:.1f}% - above 85%", "credit score 612 with a two-wheeler loan default / repossession",
         "only 1 year in current job; net income below a typical floor for this ticket size"])
    return a, docs, expect


def build_personal(positive: bool):
    a = PER_POS if positive else PER_NEG
    if positive:
        amount, months, rate, active, declared_income = 500_000.00, 36, 13.00, 1, None
    else:
        amount, months, rate, active, declared_income = 900_000.00, 48, 14.50, 4, 95_000.00
    app, emi = application_pages(
        a, "Personal Loan", amount, months, rate,
        "Home renovation" if positive else "Debt consolidation",
        [], ["PAN and Aadhaar", "Pay slips for six months and Form 16", "Savings account statements (6 months)",
             "Credit bureau report"],
        existing_emi=0.0 if positive else 31_400.00, active_unsecured=active)
    # negative: statement salary credits do not match the declared/slip income
    credit = a.net if positive else 48_200.00
    docs = {
        "01_loan_application_form.pdf": app,
        "02_identity_proof_pan_aadhaar.pdf": identity_pages(a),
        "03_income_proof_salary_form16.pdf": salary_pages(a),
        "04_bank_statements_6_months.pdf": bank_statement_pages(
            a, credit, extra_debits=() if positive else
            (("03", "EMI PL-QUICKCASH", 11_200.00), ("07", "EMI PL-FINSTAR", 9_400.00),
             ("11", "EMI CC-EMI", 6_300.00), ("16", "EMI PL-ZIPLOAN", 4_500.00))),
        "05_credit_report.pdf": credit_report_pages(
            a, 745 if positive else 688,
            ["Credit card - Rs 300,000 limit, current (1 active unsecured facility)"] if positive else
            ["Personal loan QuickCash - Rs 350,000, EMI 11,200, 45 days past due 05-2026",
             "Personal loan FinStar - Rs 280,000, EMI 9,400, current",
             "Personal loan ZipLoan - Rs 120,000, EMI 4,500, current",
             "Credit card - Rs 180,000 limit, 92% utilised, EMI 6,300 (4 active unsecured facilities)"],
            ["None"] if positive else ["None"],
            delinquency="None in the last 12 months" if positive else "45 days (QuickCash personal loan, 05-2026)"),
    }
    expect = (
        ["ELIGIBLE", f"age {a.age}; salaried {a.years_in_job} years", f"EMI-to-income {emi / a.net * 100:.1f}% (EMI {money(emi)} / net {money(a.net)})",
         "credit score 745, no delinquency in 12 months", f"salary credits {money(a.net)} in the bank statement match the slips",
         "1 active unsecured loan", "KYC complete"]
        if positive else
        ["NOT_ELIGIBLE", f"EMI-to-income {(emi + 31_400) / a.net * 100:.1f}% including existing EMIs - above 40%",
         "credit score 688 with a 45-day delinquency in 05-2026", "4 active unsecured loans (limit 3)",
         f"bank statement salary credits {money(credit)} do NOT match the slips' net pay {money(a.net)}"])
    return a, docs, expect



# name -> (product, builder). Product keys match doc_templates.json sets and
# the email connector; the engine type is the product without "_loan".
PACK_SPECS = {
    "home_loan_application_positive":     ("home_loan",     lambda: build_home(True)),
    "home_loan_application_negative":     ("home_loan",     lambda: build_home(False)),
    "vehicle_loan_application_positive":  ("vehicle_loan",  lambda: build_vehicle(True)),
    "vehicle_loan_application_negative":  ("vehicle_loan",  lambda: build_vehicle(False)),
    "personal_loan_application_positive": ("personal_loan", lambda: build_personal(True)),
    "personal_loan_application_negative": ("personal_loan", lambda: build_personal(False)),
}
