"""Regenerate the sample loan-processing kit.

    python demo_kit/loan_kit/build_kit.py

Everything under `bundles/` is written from here, so the arithmetic in the
documents is computed rather than typed: a clean bundle reconciles to the last
paisa, and a defective one carries exactly the defects seeded below and no
others. That is what makes the kit safe to run in front of a client — the
engine's findings are known in advance.

The documents are synthetic. Every page carries a SPECIMEN stamp, the
identifiers are obviously fake, and no figure comes from a real customer.
"""

from __future__ import annotations

import csv
import re
import shutil
import sys
from datetime import date, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from minipdf import Pdf, Page          # noqa: E402
from minixlsx import Sheet, b, m, n, save          # noqa: E402

KIT = Path(__file__).resolve().parent
BUNDLES = KIT / "bundles"
BUNDLES_XL = KIT / "bundles_excel"

LEFT, RIGHT = 56.0, 539.0
STAMP = ("SPECIMEN - synthetic demo data generated by build_kit.py. "
         "Not a real customer, account or document.")


def money(v: float) -> str:
    return f"{v:,.2f}"


def emi_for(principal: float, annual_rate: float, months: int) -> float:
    r = annual_rate / 1200.0
    return round(principal * r * (1 + r) ** months / ((1 + r) ** months - 1), 2)


def amortise(principal: float, annual_rate: float, emi: float,
             first_due: date, rows: int) -> list[dict]:
    """The schedule the engine will recompute, row by row, in exactly this way."""
    r = annual_rate / 1200.0
    out, balance, due = [], principal, first_due
    for n in range(1, rows + 1):
        interest = round(balance * r, 2)
        principal_part = round(emi - interest, 2)
        balance = round(balance - principal_part, 2)
        out.append({"no": n, "due": due.isoformat(), "emi": emi,
                    "interest": interest, "principal": principal_part,
                    "balance": balance})
        due = _add_month(due)
    return out


def _add_month(d: date) -> date:
    year, month = (d.year + 1, 1) if d.month == 12 else (d.year, d.month + 1)
    return date(year, month, min(d.day, 28))


# ── shared page furniture ────────────────────────────────────────────────────

def _header(p: Page, institution: str, title: str, subtitle: str = "") -> float:
    p.band(LEFT, 48, RIGHT, 34)
    p.text(LEFT + 10, 70, institution, 12, bold=True)
    p.right(RIGHT - 10, 70, title, 12, bold=True)
    if subtitle:
        p.right(RIGHT, 98, subtitle, 8, gray=0.35)
    return 116.0


def _footer(p: Page) -> None:
    p.rule(LEFT, 790, RIGHT, 0.5, 0.8)
    p.text(LEFT, 802, STAMP, 7, gray=0.45)


def _labelled(p: Page, y: float, label: str, value: str,
              money_col: float | None = None, bold: bool = False) -> float:
    """A `Label      Value` row — the shape `loan_extractors._labelled` reads."""
    p.text(LEFT, y, label, 9, bold=bold)
    if money_col is not None:
        p.right(money_col, y, value, 9, bold=bold)
    else:
        p.text(LEFT + 190, y, value, 9, bold=bold)
    return y + 16


# ── sanction letter ──────────────────────────────────────────────────────────

def sanction_letter(path: Path, bank: str, loan_id: str, borrower: str,
                    address: str, product: str, principal: float, rate: float,
                    months: int, emi: float, fee: float, first_emi: str,
                    issued: str) -> None:
    pdf = Pdf()
    p = pdf.page()
    y = _header(p, bank, "SANCTION LETTER", "Ref " + loan_id + "/SL")

    p.text(LEFT, y, "Date: " + issued, 9)
    y += 22
    p.text(LEFT, y, "To: " + borrower, 9, bold=True)
    y += 14
    p.text(LEFT, y, address, 9, gray=0.3)
    y += 26
    p.text(LEFT, y, "Dear Applicant,", 9)
    y += 18
    p.text(LEFT, y, "We are pleased to inform you that your loan application has "
                    "been sanctioned on the following terms.", 9)
    y += 26

    p.rule(LEFT, y - 10, RIGHT)
    y = _labelled(p, y, "Loan Account No", loan_id)
    y = _labelled(p, y, "Product", product)
    y = _labelled(p, y, "Sanctioned Amount (Rs)", money(principal), 330)
    y = _labelled(p, y, "Interest Rate", str(rate) + "% per annum (floating)")
    y = _labelled(p, y, "Tenure", str(months) + " months")
    y = _labelled(p, y, "EMI (Rs)", money(emi), 330)
    y = _labelled(p, y, "Processing Fee (Rs)", money(fee), 330)
    y = _labelled(p, y, "First EMI Date", first_emi)
    p.rule(LEFT, y - 6, RIGHT)
    y += 18

    for line in (
        "1. The EMI stated above is derived from the sanctioned amount, the rate "
        "of interest and the tenure.",
        "2. Disbursement is subject to completion of documentation and creation "
        "of security to the satisfaction of the Bank.",
        "3. The rate is floating and may be reset in line with the external "
        "benchmark notified from time to time.",
    ):
        p.text(LEFT, y, line, 8.5, gray=0.2)
        y += 15

    y += 30
    p.text(LEFT, y, "For " + bank, 9)
    p.text(LEFT, y + 34, "Authorised Signatory", 9, gray=0.35)
    _footer(p)
    pdf.save(path)


# ── salary slip ──────────────────────────────────────────────────────────────

def salary_slip(path: Path, employer: str, period: str, employee: str,
                employee_id: str, designation: str, basic: float, hra: float,
                special: float, pf: float, tax: float,
                gross: float | None = None, deductions: float | None = None,
                net_pay: float | None = None) -> None:
    gross = round(basic + hra + special, 2) if gross is None else gross
    deductions = round(pf + tax, 2) if deductions is None else deductions
    net_pay = round(gross - deductions, 2) if net_pay is None else net_pay

    pdf = Pdf()
    p = pdf.page()
    y = _header(p, employer, "SALARY SLIP - " + period.upper(),
                "Computer generated statement of earnings")

    # `Employee` must precede `Employee ID`: the reader matches on the row's
    # leading text and keeps the first row that starts with the label.
    y = _labelled(p, y, "Employee", employee)
    y = _labelled(p, y, "Employee ID", employee_id)
    y = _labelled(p, y, "Designation", designation)
    y += 14

    p.band(LEFT, y - 12, RIGHT, 18)
    p.text(LEFT + 6, y, "EARNINGS", 9, bold=True)
    p.right(330, y, "Amount (Rs)", 9, bold=True)
    y += 24
    y = _labelled(p, y, "Basic", money(basic), 330)
    y = _labelled(p, y, "HRA", money(hra), 330)
    y = _labelled(p, y, "Special Allowance", money(special), 330)
    p.rule(LEFT, y - 10, 330)
    y = _labelled(p, y, "Gross Earnings", money(gross), 330, True)
    y += 16

    p.band(LEFT, y - 12, RIGHT, 18)
    p.text(LEFT + 6, y, "DEDUCTIONS", 9, bold=True)
    p.right(330, y, "Amount (Rs)", 9, bold=True)
    y += 24
    y = _labelled(p, y, "Provident Fund", money(pf), 330)
    y = _labelled(p, y, "Income Tax (TDS)", money(tax), 330)
    p.rule(LEFT, y - 10, 330)
    y = _labelled(p, y, "Total Deductions", money(deductions), 330, True)
    y += 22

    p.rule(LEFT, y - 12, 330, 1.0, 0.4)
    y = _labelled(p, y, "NET PAY", money(net_pay), 330, True)
    y += 22
    p.text(LEFT, y, "Credited to the salary account on the last working day of "
                    "the month.", 8.5, gray=0.3)
    _footer(p)
    pdf.save(path)


# ── EMI repayment schedule ───────────────────────────────────────────────────

COLS = {"no": 78.0, "due": 96.0, "emi": 275.0, "interest": 355.0,
        "principal": 445.0, "balance": 539.0}


def emi_schedule(path: Path, bank: str, loan_id: str, borrower: str,
                 principal: float, rate: float, months: int, emi: float,
                 schedule: list[dict], stated_totals: dict | None = None) -> None:
    pdf = Pdf()
    p = pdf.page()
    y = _header(p, bank, "EMI REPAYMENT SCHEDULE",
                "First " + str(len(schedule)) + " of " + str(months) + " instalments")

    p.text(LEFT, y, "A/c: " + loan_id + "   Borrower: " + borrower +
           "   Principal Rs " + money(principal), 9)
    y += 15
    p.text(LEFT, y, "Rate " + str(rate) + "% per annum   EMI Rs " + money(emi) +
           "   Tenure " + str(months) + " months", 9)
    y += 26

    p.band(LEFT, y - 12, RIGHT, 18)
    p.right(COLS["no"], y, "No", 8.5, bold=True)
    p.text(COLS["due"], y, "Due Date", 8.5, bold=True)
    for key, label in (("emi", "EMI (Rs)"), ("interest", "Interest"),
                       ("principal", "Principal"), ("balance", "Balance")):
        p.right(COLS[key], y, label, 8.5, bold=True)
    y += 22

    for row in schedule:
        p.right(COLS["no"], y, str(row["no"]), 8.5)
        p.text(COLS["due"], y, row["due"], 8.5)
        for key in ("emi", "interest", "principal", "balance"):
            p.right(COLS[key], y, money(row[key]), 8.5)
        y += 15

    totals = stated_totals or {
        "interest": round(sum(r["interest"] for r in schedule), 2),
        "principal": round(sum(r["principal"] for r in schedule), 2),
        "closing": schedule[-1]["balance"],
    }
    p.rule(LEFT, y - 8, RIGHT)
    y += 10
    p.text(LEFT, y, "Totals (" + str(len(schedule)) + " rows): Interest " +
           money(totals["interest"]) + " | Principal " +
           money(totals["principal"]) + " | Closing Balance " +
           money(totals["closing"]), 9, bold=True)
    _footer(p)
    pdf.save(path)


# ── loan account statement ───────────────────────────────────────────────────

SCOLS = {"date": 56.0, "ref": 130.0, "particulars": 205.0,
         "debit": 400.0, "credit": 470.0, "balance": 539.0}


def loan_statement(path: Path, bank: str, loan_id: str, borrower: str,
                   product: str, period: tuple[str, str], opening: float,
                   txns: list[dict], stated_totals: dict | None = None) -> None:
    pdf = Pdf()
    p = pdf.page()
    y = _header(p, bank, "LOAN ACCOUNT STATEMENT", "A/c " + loan_id)

    p.text(LEFT, y, "A/c: " + loan_id, 9)
    y += 15
    p.text(LEFT, y, "Borrower " + borrower + " | Product " + product, 9)
    y += 15
    p.text(LEFT, y, "Statement Period " + period[0] + " to " + period[1], 9)
    y += 15
    p.text(LEFT, y, "Opening Balance " + money(opening), 9)
    y += 26

    p.band(LEFT, y - 12, RIGHT, 18)
    p.text(SCOLS["date"], y, "Date", 8.5, bold=True)
    p.text(SCOLS["ref"], y, "Ref", 8.5, bold=True)
    p.text(SCOLS["particulars"], y, "Particulars", 8.5, bold=True)
    for key, label in (("debit", "Debit"), ("credit", "Credit"),
                       ("balance", "Balance")):
        p.right(SCOLS[key], y, label, 8.5, bold=True)
    y += 22

    for t in txns:
        p.text(SCOLS["date"], y, t["date"], 8.5)
        p.text(SCOLS["ref"], y, t["ref"], 8.5)
        p.text(SCOLS["particulars"], y, t["particulars"], 8.5)
        if t["debit"]:
            p.right(SCOLS["debit"], y, money(t["debit"]), 8.5)
        if t["credit"]:
            p.right(SCOLS["credit"], y, money(t["credit"]), 8.5)
        p.right(SCOLS["balance"], y, money(t["balance"]), 8.5)
        y += 15

    totals = stated_totals or {
        "debits": round(sum(t["debit"] for t in txns), 2),
        "credits": round(sum(t["credit"] for t in txns), 2),
        "closing": txns[-1]["balance"],
    }
    p.rule(LEFT, y - 8, RIGHT)
    y += 10
    p.text(LEFT, y, "Totals: Debits " + money(totals["debits"]) + " | Credits " +
           money(totals["credits"]) + " | Closing Balance " +
           money(totals["closing"]), 9, bold=True)
    _footer(p)
    pdf.save(path)


def loan_ledger(opening: float, rate: float, emi: float, start: date,
                periods: int, prefix: str) -> list[dict]:
    """Interest charged, EMI received, month after month — a chain that ties."""
    txns, balance, when = [], opening, start
    for i in range(periods):
        interest = round(balance * rate / 1200.0, 2)
        balance = round(balance + interest, 2)
        txns.append({"date": when.isoformat(), "ref": prefix + "%04d" % (i * 2 + 1),
                     "particulars": "Interest charged", "debit": interest,
                     "credit": 0.0, "balance": balance})
        pay = when + timedelta(days=4)
        balance = round(balance - emi, 2)
        txns.append({"date": pay.isoformat(), "ref": prefix + "%04d" % (i * 2 + 2),
                     "particulars": "EMI received - NACH", "debit": 0.0,
                     "credit": emi, "balance": balance})
        when = _add_month(when)
    return txns


# ── CSV current-account statement (the zero-token path) ──────────────────────

def current_account_csv(path: Path, opening: float, rows: list[tuple]) -> None:
    """`Date, Chq/Ref No, Narration, Withdrawal Amt, Deposit Amt, Closing Balance`

    Deliberately not the canonical header names — the reader matches columns by
    synonym, and a demo should show that rather than a hand-tailored export.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    balance = opening
    with path.open("w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(["Meridian Bank - Current Account Statement"])
        w.writerow(["Account", "MB-CA-88214301", "Customer",
                    "Halcyon Traders LLP (SPECIMEN)"])
        w.writerow([])
        w.writerow(["Date", "Chq/Ref No", "Narration", "Withdrawal Amt",
                    "Deposit Amt", "Closing Balance"])
        for when, ref, narration, debit, credit in rows:
            balance = round(balance - debit + credit, 2)
            w.writerow([when, ref, narration,
                        f"{debit:.2f}" if debit else "",
                        f"{credit:.2f}" if credit else "",
                        f"{balance:.2f}"])


def _account_rows() -> list[tuple]:
    """Two months of trading, two returned cheques, one round-tripped pair."""
    return [
        ("2026-06-01", "NEFT9001", "NEFT IN - Alderman Retail invoice 5512", 0, 486_000.00),
        ("2026-06-03", "CHQ100231", "Cheque paid - Vantage Packaging", 212_500.00, 0),
        ("2026-06-05", "UPI7741", "UPI - fuel and logistics", 18_400.00, 0),
        ("2026-06-08", "NEFT9014", "NEFT IN - Brightline Stores invoice 5518", 0, 322_750.00),
        ("2026-06-10", "CHQ100232", "INWARD CHQ RTN - insufficient funds", 141_000.00, 0),
        ("2026-06-11", "SAL0626", "Salary payout - June", 268_300.00, 0),
        ("2026-06-15", "GST0626", "GST payment - June", 96_750.00, 0),
        ("2026-06-18", "NEFT9032", "NEFT IN - Cobalt Wholesale invoice 5521", 0, 254_900.00),
        ("2026-06-22", "TRF4410", "Transfer to associate - Halcyon Exports", 300_000.00, 0),
        ("2026-06-24", "TRF4418", "Transfer from associate - Halcyon Exports", 0, 300_000.00),
        ("2026-06-27", "CHQ100233", "Cheque paid - Ridgeway Freight", 87_200.00, 0),
        ("2026-06-30", "INT0626", "Interest credited", 0, 3_180.00),
        ("2026-07-02", "NEFT9051", "NEFT IN - Alderman Retail invoice 5530", 0, 402_600.00),
        ("2026-07-04", "EMI0704", "Working capital EMI - NACH", 148_900.00, 0),
        ("2026-07-07", "UPI7802", "UPI - warehouse utilities", 22_650.00, 0),
        ("2026-07-09", "CHQ100234", "Cheque paid - Vantage Packaging", 196_400.00, 0),
        ("2026-07-12", "NEFT9068", "NEFT IN - Brightline Stores invoice 5536", 0, 288_400.00),
        ("2026-07-15", "GST0726", "GST payment - July", 101_300.00, 0),
        ("2026-07-17", "CHQ100235", "CHEQUE RETURNED - drawer signature differs", 64_800.00, 0),
        ("2026-07-21", "SAL0726", "Salary payout - July", 271_950.00, 0),
        ("2026-07-24", "NEFT9090", "NEFT IN - Cobalt Wholesale invoice 5540", 0, 219_300.00),
        ("2026-07-28", "TRF4462", "Transfer to associate - Halcyon Exports", 250_000.00, 0),
        ("2026-07-29", "TRF4470", "Transfer from associate - Halcyon Exports", 0, 250_000.00),
        ("2026-07-31", "INT0726", "Interest credited", 0, 2_940.00),
    ]


# ── KYC set (no deterministic parser — this is the model-led path) ───────────

KYC_DOCS = {
    "identity_card.txt": """SPECIMEN IDENTITY DOCUMENT - SYNTHETIC DEMO DATA
Issuing authority: Demo Identity Registry (fictional)

Name              Arjun Mehta
Date of birth     1989-04-12
Document number   XXXX XXXX 4471   (masked specimen number)
Issued            2019-08-02
Valid until       2029-08-01
Photograph        Present
Signature         Present

This document is generated for a software demonstration. It is not issued by
any authority and confers no identity.
""",
    "address_proof_utility_bill.txt": """SPECIMEN UTILITY BILL - SYNTHETIC DEMO DATA
Meridian Power Distribution (fictional utility)

Consumer name     Arjun Mehta
Service address   14/2 Lakeview Terrace, Bellandur, Bengaluru 560103
Billing period    2026-07-01 to 2026-07-31
Bill date         2026-08-04
Amount due        3,428.00
Consumer number   MPD-SPECIMEN-77412

Issued for demonstration purposes only.
""",
    "tax_identifier.txt": """SPECIMEN TAX IDENTIFIER RECORD - SYNTHETIC DEMO DATA

Name on record    Arjun Mehtaa
Date of birth     1989-04-21
Identifier        ABCDE0000F   (reserved specimen format)
Status            Active

Note for the demo: the name and the date of birth on this record differ from
the identity document in the same folder. Both discrepancies are deliberate.
""",
}


# ── Excel twins ──────────────────────────────────────────────────────────────
# Every document in the kit also exists as a .xlsx under bundles_excel/, for
# the client who says "our documents come out of the core system as
# spreadsheets". The figures are the same objects that produced the PDFs, so a
# seeded defect appears identically in both formats.
#
# Note what the pipeline does with these: `loan_extractors` has no Excel
# parser, so an .xlsx is not reconciled in code — it is read by
# `loan_processing.extract_text` (pandas + openpyxl) and sent to the model in
# full. The Excel bundles therefore demonstrate the model-led path, not the
# zero-token one. See EXPECTED.md.

def xl_sanction_letter(path: Path, spec: dict, emi: float) -> None:
    s = Sheet("Sanction Letter", widths=[30, 34])
    s.row(b(spec["bank"]), b("SANCTION LETTER"))
    s.row("Ref", spec["loan_id"] + "/SL")
    s.row("Date", spec["issued"])
    s.blank()
    s.row("To", spec["borrower"])
    s.row("Address", spec["address"])
    s.blank()
    s.row(b("Sanctioned terms"))
    s.row("Loan Account No", spec["loan_id"])
    s.row("Product", spec["product"])
    s.row("Sanctioned Amount (Rs)", m(spec["principal"]))
    s.row("Interest Rate", str(spec["rate"]) + "% per annum (floating)")
    s.row("Tenure", str(spec["months"]) + " months")
    s.row("EMI (Rs)", m(emi))
    s.row("Processing Fee (Rs)", m(spec["fee"]))
    s.row("First EMI Date", spec["first_emi"])
    s.blank()
    s.row("Note", "The EMI stated above is derived from the sanctioned "
                  "amount, the rate of interest and the tenure.")
    s.row(STAMP)
    save(s, path)


def xl_salary_slip(path: Path, employer: str, period: str, employee: str,
                   employee_id: str, designation: str, basic: float,
                   hra: float, special: float, pf: float, tax: float,
                   gross: float, deductions: float, net_pay: float) -> None:
    s = Sheet("Salary Slip", widths=[30, 20])
    s.row(b(employer), b("SALARY SLIP - " + period.upper()))
    s.blank()
    s.row("Employee", employee)
    s.row("Employee ID", employee_id)
    s.row("Designation", designation)
    s.blank()
    s.row(b("Earnings"), b("Amount (Rs)"))
    s.row("Basic", m(basic))
    s.row("HRA", m(hra))
    s.row("Special Allowance", m(special))
    s.row(b("Gross Earnings"), m(gross, bold=True))
    s.blank()
    s.row(b("Deductions"), b("Amount (Rs)"))
    s.row("Provident Fund", m(pf))
    s.row("Income Tax (TDS)", m(tax))
    s.row(b("Total Deductions"), m(deductions, bold=True))
    s.blank()
    s.row(b("NET PAY"), m(net_pay, bold=True))
    s.row(STAMP)
    save(s, path)


def xl_emi_schedule(path: Path, spec: dict, emi: float, schedule: list[dict],
                    totals: dict) -> None:
    s = Sheet("EMI Schedule", widths=[8, 14, 16, 16, 16, 18])
    s.row(b(spec["bank"]), b("EMI REPAYMENT SCHEDULE"))
    s.row("A/c", spec["loan_id"])
    s.row("Borrower", spec["borrower"])
    s.row("Principal (Rs)", m(spec["principal"]))
    s.row("Rate", str(spec["rate"]) + "% per annum")
    s.row("EMI (Rs)", m(emi))
    s.row("Tenure", str(spec["months"]) + " months")
    s.blank()
    s.row(b("No"), b("Due Date"), b("EMI (Rs)"), b("Interest"),
          b("Principal"), b("Balance"))
    for row in schedule:
        s.row(n(row["no"]), row["due"], m(row["emi"]), m(row["interest"]),
              m(row["principal"]), m(row["balance"]))
    s.blank()
    s.row(b(f"Totals ({len(schedule)} rows)"), "", "",
          m(totals["interest"], bold=True), m(totals["principal"], bold=True),
          m(totals["closing"], bold=True))
    s.row(STAMP)
    save(s, path)


def xl_loan_statement(path: Path, spec: dict, borrower: str,
                      period: tuple[str, str], txns: list[dict],
                      totals: dict) -> None:
    s = Sheet("Loan Statement", widths=[14, 14, 30, 16, 16, 18])
    s.row(b(spec["bank"]), b("LOAN ACCOUNT STATEMENT"))
    s.row("A/c", spec["loan_id"])
    s.row("Borrower", borrower)
    s.row("Product", spec["product"])
    s.row("Statement Period", period[0] + " to " + period[1])
    s.row("Opening Balance", m(spec["principal"]))
    s.blank()
    s.row(b("Date"), b("Ref"), b("Particulars"), b("Debit"), b("Credit"),
          b("Balance"))
    for t in txns:
        s.row(t["date"], t["ref"], t["particulars"],
              m(t["debit"]) if t["debit"] else "",
              m(t["credit"]) if t["credit"] else "",
              m(t["balance"]))
    s.blank()
    s.row(b("Totals"), "", "", m(totals["debits"], bold=True),
          m(totals["credits"], bold=True), m(totals["closing"], bold=True))
    s.row(STAMP)
    save(s, path)


def xl_current_account(path: Path, opening: float, rows: list[tuple]) -> None:
    s = Sheet("Current Account", widths=[14, 14, 42, 16, 16, 18])
    s.row(b("Meridian Bank - Current Account Statement"))
    s.row("Account", "MB-CA-88214301", "Customer",
          "Halcyon Traders LLP (SPECIMEN)")
    s.row("Opening Balance", m(opening))
    s.blank()
    s.row(b("Date"), b("Chq/Ref No"), b("Narration"), b("Withdrawal Amt"),
          b("Deposit Amt"), b("Closing Balance"))
    balance = opening
    for when, ref, narration, debit, credit in rows:
        balance = round(balance - debit + credit, 2)
        s.row(when, ref, narration,
              m(debit) if debit else "", m(credit) if credit else "",
              m(balance))
    s.row(STAMP)
    save(s, path)


def xl_from_text(path: Path, title: str, body: str) -> None:
    """A text document as a spreadsheet: `Label | Value` where the source has
    that shape, and one cell per line where it does not."""
    s = Sheet(title[:31], widths=[28, 64])
    for line in body.splitlines():
        stripped = line.strip()
        if not stripped:
            s.blank()
            continue
        # Two or more spaces separate a label from its value in these files.
        parts = re.split(r"\s{2,}", stripped, maxsplit=1)
        if len(parts) == 2:
            s.row(b(parts[0]), parts[1])
        else:
            s.row(stripped)
    save(s, path)


# ── bundle definitions ───────────────────────────────────────────────────────
# One entry per folder under bundles/. Everything the demo shows is set here:
# the product terms, the payslip that decides FOIR, and — where the bundle is
# meant to fail — exactly which defect is seeded into which document.

BANK = "Northbridge Bank Ltd (SPECIMEN)"

BUNDLE_SPECS: dict[str, dict] = {
    "home_loan_positive": dict(
        bank=BANK, loan_id="HL-2026-004471", borrower="Priya Raghavan",
        address="14 Ashwood Lane, Indiranagar, Bengaluru 560038",
        product="Home Loan (Floating)",
        principal=4_500_000.00, rate=8.75, months=240, fee=22_500.00,
        first_emi="2026-05-05", issued="2026-03-18", first_due=date(2026, 5, 5),
        employer="Northwind Systems Pvt Ltd (SPECIMEN)", period="March 2026",
        employee_id="EMP-40118", designation="Engineering Manager",
        basic=62_000.00, hra=24_800.00, special=41_200.00,
        pf=7_440.00, tax=12_110.00,
        statement_months=6,
    ),
    "home_loan_negative": dict(
        bank=BANK, loan_id="HL-2026-004902", borrower="Arjun Mehta",
        address="14/2 Lakeview Terrace, Bellandur, Bengaluru 560103",
        product="Home Loan (Floating)",
        principal=3_200_000.00, rate=9.40, months=180, fee=16_000.00,
        first_emi="2026-06-05", issued="2026-04-22", first_due=date(2026, 6, 5),
        employer="Kestrel Logistics Pvt Ltd (SPECIMEN)", period="March 2026",
        employee_id="KL-2287", designation="Depot Supervisor",
        basic=30_000.00, hra=12_000.00, special=18_000.00,
        pf=3_600.00, tax=2_900.00,
        statement_months=6,
        # The four seeded defects, one per document.
        emi_understated=2_400.00,          # sanction letter
        net_pay_overstated=5_000.00,       # salary slip
        tamper_row=7, tamper_amount=18_000.00,   # EMI schedule
        statement_closing_delta=12_500.00,       # loan statement
    ),
    "vehicle_loan_positive": dict(
        bank=BANK, loan_id="VL-2026-118820", borrower="Sneha Kulkarni",
        address="7 Palm Grove Road, Kothrud, Pune 411038",
        product="Vehicle Loan (Fixed)",
        principal=1_150_000.00, rate=9.85, months=60, fee=8_500.00,
        first_emi="2026-07-07", issued="2026-05-29", first_due=date(2026, 7, 7),
        employer="Aster Health Services Pvt Ltd (SPECIMEN)", period="April 2026",
        employee_id="AH-9043", designation="Clinical Data Lead",
        basic=48_000.00, hra=19_200.00, special=32_800.00,
        pf=5_760.00, tax=9_140.00,
        statement_months=0,
    ),
    # The servicing story: the sanction terms and the schedule are sound, but
    # the loan account does not tie and the payslip's deductions column is
    # short. Neither is a policy failure — FOIR passes — and neither is the
    # home loan's tampered EMI.
    "vehicle_loan_negative": dict(
        bank=BANK, loan_id="VL-2026-119045", borrower="Karan Bhatia",
        address="52 Nehru Nagar, Sector 21, Gurugram 122016",
        product="Vehicle Loan (Fixed)",
        principal=1_450_000.00, rate=10.75, months=60, fee=11_000.00,
        first_emi="2026-08-12", issued="2026-06-30", first_due=date(2026, 8, 12),
        employer="Sierra Foods Pvt Ltd (SPECIMEN)", period="June 2026",
        employee_id="SF-7716", designation="Regional Sales Manager",
        basic=40_000.00, hra=16_000.00, special=24_000.00,
        pf=4_800.00, tax=6_200.00,
        statement_months=4,
        # Two seeded defects, both inside a document's own arithmetic.
        deductions_understated=2_000.00,                          # salary slip
        statement_break_index=5, statement_break_amount=9_500.00,  # statement
    ),
    "mortgage_loan_positive": dict(
        bank=BANK, loan_id="LAP-2026-007713", borrower="Devendra Iyer",
        address="221 Marine Crescent, Fort, Mumbai 400001",
        product="Loan Against Property (Floating)",
        principal=6_800_000.00, rate=10.25, months=144, fee=34_000.00,
        first_emi="2026-08-10", issued="2026-06-15", first_due=date(2026, 8, 10),
        employer="Trident Textiles Ltd (SPECIMEN)", period="May 2026",
        employee_id="TT-1177", designation="General Manager - Operations",
        basic=96_000.00, hra=38_400.00, special=101_600.00,
        pf=11_520.00, tax=24_480.00,
        statement_months=4,
    ),
    # The file the branch assembled from two different loans: every figure in
    # it is arithmetically sound, but the documents do not describe one
    # consistent application. A different failure class from the home loan's
    # tampered figures, and the reason the mortgage box has its own negative.
    "mortgage_loan_negative": dict(
        bank=BANK, loan_id="LAP-2026-008145", borrower="Meera Sundaram",
        address="8 Chandini Chowk Road, Alipore, Kolkata 700027",
        product="Loan Against Property (Floating)",
        principal=5_600_000.00, rate=10.60, months=120, fee=28_000.00,
        first_emi="2026-09-08", issued="2026-07-21", first_due=date(2026, 9, 8),
        employer="Corvus Instruments Pvt Ltd (SPECIMEN)", period="June 2026",
        employee_id="CI-5540", designation="Head of Quality",
        basic=78_000.00, hra=31_200.00, special=92_800.00,
        pf=9_360.00, tax=19_640.00,
        statement_months=4,
        # Two seeded defects, neither of them an arithmetic error.
        statement_borrower="Meera R Sundaram",   # name disagrees with the file
        schedule_totals_delta=4_000.00,          # totals line vs its own rows
    ),
    "personal_loan_positive": dict(
        bank=BANK, loan_id="PL-2026-551997", borrower="Tara Venkatesh",
        address="26 Rosewood Street, Adyar, Chennai 600020",
        product="Personal Loan (Fixed, unsecured)",
        principal=600_000.00, rate=14.75, months=48, fee=9_000.00,
        first_emi="2026-06-20", issued="2026-05-04", first_due=date(2026, 6, 20),
        employer="Lumen Analytics Pvt Ltd (SPECIMEN)", period="April 2026",
        employee_id="LA-3391", designation="Senior Analyst",
        basic=34_000.00, hra=13_600.00, special=20_400.00,
        pf=4_080.00, tax=5_920.00,
        statement_months=0,
    ),
    # Every figure reconciles; the application still fails on policy, because
    # the EMI takes more than half the take-home pay. Arithmetic and eligibility
    # are separate findings, and this bundle is the one that shows it.
    "personal_loan_negative": dict(
        bank=BANK, loan_id="PL-2026-553104", borrower="Rehan Qureshi",
        address="9B Silver Oak Apartments, Salt Lake, Kolkata 700091",
        product="Personal Loan (Fixed, unsecured)",
        principal=900_000.00, rate=15.50, months=48, fee=13_500.00,
        first_emi="2026-07-15", issued="2026-06-02", first_due=date(2026, 7, 15),
        employer="Fairmont Retail Pvt Ltd (SPECIMEN)", period="April 2026",
        employee_id="FR-6612", designation="Store Manager",
        basic=26_000.00, hra=10_400.00, special=15_600.00,
        pf=3_120.00, tax=1_880.00,
        statement_months=0,
    ),
}


def _schedule_totals(schedule: list[dict]) -> dict:
    return {"interest": round(sum(r["interest"] for r in schedule), 2),
            "principal": round(sum(r["principal"] for r in schedule), 2),
            "closing": schedule[-1]["balance"]}


def _ledger_totals(txns: list[dict]) -> dict:
    return {"debits": round(sum(t["debit"] for t in txns), 2),
            "credits": round(sum(t["credit"] for t in txns), 2),
            "closing": txns[-1]["balance"]}


def build_bundle(out: Path, spec: dict, xl_out: Path | None = None) -> dict:
    """Write one applicant's document set. Returns the facts the runbook quotes.

    `xl_out` writes the same documents again as .xlsx, from the same computed
    figures — so a seeded defect reads identically in both formats.
    """
    true_emi = emi_for(spec["principal"], spec["rate"], spec["months"])
    printed_emi = round(true_emi - spec.get("emi_understated", 0.0), 2)

    sanction_letter(out / "01_sanction_letter.pdf", spec["bank"],
                    spec["loan_id"], spec["borrower"], spec["address"],
                    spec["product"], spec["principal"], spec["rate"],
                    spec["months"], printed_emi, spec["fee"],
                    spec["first_emi"], spec["issued"])
    if xl_out:
        xl_sanction_letter(xl_out / "01_sanction_letter.xlsx", spec, printed_emi)

    gross = spec["basic"] + spec["hra"] + spec["special"]
    deductions = spec["pf"] + spec["tax"]
    # An understated deductions column flatters take-home pay while every other
    # figure on the slip still adds up — net pay follows the stated total, so
    # only the deductions line is wrong.
    stated_deductions = round(deductions - spec.get("deductions_understated", 0.0), 2)
    printed_net = round(gross - stated_deductions
                        + spec.get("net_pay_overstated", 0.0), 2)
    salary_slip(out / "02_salary_slip.pdf", spec["employer"], spec["period"],
                spec["borrower"], spec["employee_id"], spec["designation"],
                basic=spec["basic"], hra=spec["hra"], special=spec["special"],
                pf=spec["pf"], tax=spec["tax"], deductions=stated_deductions,
                net_pay=printed_net)
    if xl_out:
        xl_salary_slip(xl_out / "02_salary_slip.xlsx", spec["employer"],
                       spec["period"], spec["borrower"], spec["employee_id"],
                       spec["designation"], spec["basic"], spec["hra"],
                       spec["special"], spec["pf"], spec["tax"], gross,
                       stated_deductions, printed_net)

    schedule = amortise(spec["principal"], spec["rate"], true_emi,
                        spec["first_due"], 12)
    totals = None
    if spec.get("schedule_totals_delta"):
        # The rows are all correct; the totals line under them is not. The
        # reader re-adds the column and catches the difference.
        totals = {"interest": round(sum(r["interest"] for r in schedule)
                                    + spec["schedule_totals_delta"], 2),
                  "principal": round(sum(r["principal"] for r in schedule), 2),
                  "closing": schedule[-1]["balance"]}
    if spec.get("tamper_row"):
        # State the true totals, then alter one closing balance: the chain
        # breaks at that row and again at the next, where it re-joins the
        # true figures. Nothing else in the document moves.
        totals = {"interest": round(sum(r["interest"] for r in schedule), 2),
                  "principal": round(sum(r["principal"] for r in schedule), 2),
                  "closing": schedule[-1]["balance"]}
        i = spec["tamper_row"] - 1
        schedule[i]["balance"] = round(schedule[i]["balance"]
                                       - spec["tamper_amount"], 2)
    emi_schedule(out / "03_emi_schedule.pdf", spec["bank"], spec["loan_id"],
                 spec["borrower"], spec["principal"], spec["rate"],
                 spec["months"], true_emi, schedule, totals)
    if xl_out:
        xl_emi_schedule(xl_out / "03_emi_schedule.xlsx", spec, true_emi,
                        schedule, totals or _schedule_totals(schedule))

    if spec.get("statement_months"):
        ledger = loan_ledger(spec["principal"], spec["rate"], true_emi,
                             spec["first_due"], spec["statement_months"], "TXN")
        stated = None
        if spec.get("statement_closing_delta"):
            stated = {"debits": round(sum(t["debit"] for t in ledger), 2),
                      "credits": round(sum(t["credit"] for t in ledger), 2),
                      "closing": round(ledger[-1]["balance"]
                                       - spec["statement_closing_delta"], 2)}
        if spec.get("statement_break_index"):
            # One running balance that does not follow from the row above it.
            # The totals still tie, because a middle row is altered and the
            # closing balance is not — the break is the only finding.
            i = spec["statement_break_index"] - 1
            ledger[i]["balance"] = round(ledger[i]["balance"]
                                         - spec["statement_break_amount"], 2)

        last = ledger[-1]["date"]
        # `statement_borrower` seeds a name that disagrees with the rest of the
        # file — the documents reconcile individually and still do not describe
        # one applicant.
        borrower = spec.get("statement_borrower") or spec["borrower"]
        period = (ledger[0]["date"], last)
        loan_statement(out / "04_loan_account_statement.pdf", spec["bank"],
                       spec["loan_id"], borrower, spec["product"],
                       period, spec["principal"], ledger, stated)
        if xl_out:
            xl_loan_statement(xl_out / "04_loan_account_statement.xlsx", spec,
                              borrower, period, ledger,
                              stated or _ledger_totals(ledger))

    return {"emi": true_emi, "printed_emi": printed_emi,
            "net_pay": printed_net,
            "foir": round(printed_emi / printed_net * 100, 2)}


# ── KYC set — no deterministic parser, so this is the model-led path ────────

KYC_DOCS = {
    "identity_card.txt": """SPECIMEN IDENTITY DOCUMENT - SYNTHETIC DEMO DATA
Issuing authority: Demo Identity Registry (fictional)

Name              Arjun Mehta
Date of birth     1989-04-12
Document number   XXXX XXXX 4471   (masked specimen number)
Issued            2019-08-02
Valid until       2029-08-01
Photograph        Present
Signature         Present

This document is generated for a software demonstration. It is not issued by
any authority and confers no identity.
""",
    "address_proof_utility_bill.txt": """SPECIMEN UTILITY BILL - SYNTHETIC DEMO DATA
Meridian Power Distribution (fictional utility)

Consumer name     Arjun Mehta
Service address   14/2 Lakeview Terrace, Bellandur, Bengaluru 560103
Billing period    2026-07-01 to 2026-07-31
Bill date         2026-08-04
Amount due        3,428.00
Consumer number   MPD-SPECIMEN-77412

Issued for demonstration purposes only.
""",
    "tax_identifier.txt": """SPECIMEN TAX IDENTIFIER RECORD - SYNTHETIC DEMO DATA

Name on record    Arjun Mehtaa
Date of birth     1989-04-21
Identifier        ABCDE0000F   (reserved specimen format)
Status            Active

The name and the date of birth on this record differ from the identity
document in the same folder. Both discrepancies are deliberate: the KYC box
should report them rather than reconcile them away.
""",
    "expired_employment_letter.txt": """SPECIMEN EMPLOYMENT LETTER - SYNTHETIC DEMO DATA
Kestrel Logistics Pvt Ltd (fictional employer)

To whom it may concern

Arjun Mehta has been employed as Depot Supervisor since 2021-03-01.
Monthly gross remuneration: 60,000.00

Letter valid until   2026-02-28
Signed               2025-08-28

Issued for demonstration purposes only.
""",
}

GENERAL_NOTE = """SPECIMEN CREDIT NOTE - SYNTHETIC DEMO DATA

From:    Relationship Manager, Northbridge Bank Ltd (SPECIMEN)
Subject: Halcyon Traders LLP - working capital review

The current account statement for June and July 2026 is attached, together
with the sanction letter for the promoter's home loan.

Points the committee asked about:
  - two cheques were returned in the period, one for insufficient funds;
  - transfers to and from an associate concern reverse within two days;
  - the promoter's personal EMI obligation is served from the same group.

Please summarise what the documents actually support, and say what is missing.
"""


# ── kit assembly ─────────────────────────────────────────────────────────────

def main() -> None:
    for root in (BUNDLES, BUNDLES_XL):
        if root.exists():
            shutil.rmtree(root)
        root.mkdir(parents=True)

    # Where the UI's sample preset points its output path. Reports from a demo
    # land here, beside the documents that produced them; git carries the
    # folder via .gitkeep because it cannot carry an empty directory.
    output = KIT / "output"
    output.mkdir(exist_ok=True)
    (output / ".gitkeep").write_text("", encoding="utf-8")

    facts: dict[str, dict] = {}
    for name, spec in BUNDLE_SPECS.items():
        folder = BUNDLES / name
        xl_folder = BUNDLES_XL / name
        folder.mkdir(parents=True, exist_ok=True)
        xl_folder.mkdir(parents=True, exist_ok=True)
        facts[name] = build_bundle(folder, spec, xl_folder)

    # One folder holding two applicants — the engine has to split them by loan
    # account number rather than check one person's EMI against another's pay.
    for root, suffix in ((BUNDLES, "*.pdf"), (BUNDLES_XL, "*.xlsx")):
        both = root / "home_loan_two_applicants"
        both.mkdir(parents=True, exist_ok=True)
        for src, tag in ((root / "home_loan_positive", "raghavan"),
                         (root / "home_loan_negative", "mehta")):
            for f in sorted(src.glob(suffix)):
                shutil.copy(f, both / (tag + "_" + f.name))

    account = BUNDLES / "account_statement_csv"
    current_account_csv(account / "current_account_jun_jul_2026.csv",
                        1_284_500.00, _account_rows())
    xl_current_account(
        BUNDLES_XL / "account_statement_csv" / "current_account_jun_jul_2026.xlsx",
        1_284_500.00, _account_rows())

    kyc = BUNDLES / "kyc_set"
    kyc.mkdir(parents=True, exist_ok=True)
    for name, body in KYC_DOCS.items():
        (kyc / name).write_text(body, encoding="utf-8")
        xl_from_text(BUNDLES_XL / "kyc_set" / (Path(name).stem + ".xlsx"),
                     Path(name).stem.replace("_", " ").title(), body)

    # The General box takes whatever arrives: a CSV, a PDF and a covering note.
    general = BUNDLES / "general_mixed"
    general.mkdir(parents=True, exist_ok=True)
    shutil.copy(account / "current_account_jun_jul_2026.csv",
                general / "current_account_jun_jul_2026.csv")
    shutil.copy(BUNDLES / "home_loan_positive" / "01_sanction_letter.pdf",
                general / "sanction_letter.pdf")
    (general / "covering_note.txt").write_text(GENERAL_NOTE, encoding="utf-8")

    general_xl = BUNDLES_XL / "general_mixed"
    general_xl.mkdir(parents=True, exist_ok=True)
    shutil.copy(BUNDLES_XL / "account_statement_csv"
                / "current_account_jun_jul_2026.xlsx",
                general_xl / "current_account_jun_jul_2026.xlsx")
    shutil.copy(BUNDLES_XL / "home_loan_positive" / "01_sanction_letter.xlsx",
                general_xl / "sanction_letter.xlsx")
    xl_from_text(general_xl / "covering_note.xlsx", "Covering Note", GENERAL_NOTE)

    print("Kit written to", BUNDLES)
    for name in sorted(facts):
        f = facts[name]
        line = ("  %-22s EMI %s  net %s  FOIR %.2f%%"
                % (name, money(f["printed_emi"]), money(f["net_pay"]), f["foir"]))
        if f["printed_emi"] != f["emi"]:
            line += "  (amortised EMI " + money(f["emi"]) + ")"
        print(line)
    print("  %-22s %d documents" % (
        "home_loan_two_applicants",
        len(list((BUNDLES / "home_loan_two_applicants").glob("*.pdf")))))
    print("  %-22s 1 CSV, 24 transactions" % "account_statement_csv")
    print("  %-22s %d text documents" % ("kyc_set", len(KYC_DOCS)))
    print("  %-22s 3 assorted documents" % "general_mixed")

    xl_count = len(list(BUNDLES_XL.rglob("*.xlsx")))
    print("\nExcel twins written to", BUNDLES_XL)
    print("  %d .xlsx documents across %d bundles"
          % (xl_count, len(list(BUNDLES_XL.iterdir()))))
    print("\nVerify with: python demo_kit/loan_kit/verify_kit.py")


if __name__ == "__main__":
    main()
